SET FOREIGN_KEY_CHECKS=0;
TRUNCATE `Addresses`;
SET FOREIGN_KEY_CHECKS=1;

SET FOREIGN_KEY_CHECKS=0;
TRUNCATE `SocialInsurances`;
SET FOREIGN_KEY_CHECKS=1;

SET FOREIGN_KEY_CHECKS=0;
TRUNCATE `Citizens`;
SET FOREIGN_KEY_CHECKS=1;
